# Trigger on every push to the main branch
trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
# STAGE 1: Build
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build React App'
    pool:
      name: Default   # kendi self-hosted pool'un
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build project'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'build'              # CRA için build çıktısı
        artifact: 'build-artifact'       # artifact ismi
      displayName: 'Publish pipeline artifact'

# STAGE 2: Deploy
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure Static Web Apps'
    pool:
      name: Default   # kendi self-hosted pool'un
    steps:
    # 1. Pipeline artifact'i indir
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'build-artifact'
        path: '$(Pipeline.Workspace)/build-artifact'

    # 2. AzureStaticWebApp Docker image'i pull et (timeout önlemi)
    - script: docker pull mcr.microsoft.com/appsvc/staticappsclient:stable
      displayName: 'Pull Azure Static Web Apps client image'

    # 3. Deploy
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '$(Pipeline.Workspace)/build-artifact'
        output_location: '.'        # build klasörünün içinde index.html var
        skip_app_build: true
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
